### ISSUE TITLE
some unity package fails to decode

### ISSUE THREAD

**Issue by art0007i** [ticpu/rust-unityextractor#1]
for some reason I have managed to find a UnityPackage in which all files have `\n00` at the end of them, which means that the trim function doesn't trim it since there is zeros past the new line.

I made a small change to the program to print out errors like this, and this is what it said:

```2024-01-17T00:46:54.457Z ERROR [rust_unityextractor] Failed to extract file "Assets/MagicaCloth2/Scripts/Core/Reduction/StepReductionBase.cs\n00", reaason: Os { code: 123, kind: InvalidFilename, message: "The filename, directory name, or volume label syntax is incorrect." }```

**Comment by ticpu** [comment]
There's now much more edge-case handling e87a7d49e467a88644943327150674b00e7e95e3 should fix the issue.  I also added error reporting for failed writes.

Thanks for the report!
